name: Ardeev_Dmitry_Foodgram

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: qwerty
          POSTGRES_DB: django
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Flake8
        run: |
          flake8 backend/

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Checking PostgreSQL availability on db:5432..."
          for i in {1..30}; do
            if pg_isready -h db -p 5432 -U django -d django; then
              echo "PostgreSQL is ready!"
              break
            else
              echo "db:5432 - no response (attempt $i/30)"
              sleep 5
            fi
          done
          if ! pg_isready -h db -p 5432 -U django -d django; then
            echo "Error: PostgreSQL failed to start after 150 seconds"
            exit 1
          fi

      - name: Run migrations
        env:
          DB_HOST: db
          DB_PORT: 5432
          POSTGRES_USER: django
          POSTGRES_PASSWORD: qwerty
          POSTGRES_DB: django
          SECRET_KEY: django-insecure-6&-%5ecbx&al2#xr!*@-og6al!kp8qcl%1_k7auy#i6e@(2+iz
          ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
          DEBUG: False
        run: |
          cd backend
          python manage.py migrate

      - name: Load test data
        env:
          DB_HOST: db
          DB_PORT: 5432
          POSTGRES_USER: django
          POSTGRES_PASSWORD: qwerty
          POSTGRES_DB: django
          SECRET_KEY: django-insecure-6&-%5ecbx&al2#xr!*@-og6al!kp8qcl%1_k7auy#i6e@(2+iz
          ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
          DEBUG: False
        run: |
          cd backend
          python manage.py call_to_bd

  build_and_push_backend_to_docker_hub:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram-backend:latest

  build_and_push_frontend_to_docker_hub:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram-frontend:latest
